NAME : Pallavi Pawar
BRANCH :CO

TASK 3

In [2]:
import numpy as np

# 1. Create 1D and 2D arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([[10, 20], [30, 40]])

print("Array a:", a)
print("Array b:\n", b)

# 2. Array shape
print("Shape of b:", b.shape)

# 3. Array data type
print("Data type of a:", a.dtype)

# 4. Zeros array
z = np.zeros((2, 3))
print("Zeros array:\n", z)

# 5. Ones array
o = np.ones((2, 2))
print("Ones array:\n", o)

# 6. Identity matrix
i = np.eye(3)
print("Identity Matrix:\n", i)

# 7. Reshape
reshaped = np.reshape(a, (5, 1))
print("Reshaped a to 5x1:\n", reshaped)

# 8. Array slicing
print("Sliced a[1:4]:", a[1:4])

# 9. Element-wise addition
c = np.array([5, 4, 3, 2, 1])
print("Addition a + c:", a + c)

# 10. Element-wise multiplication
print("Multiplication a * c:", a * c)

# 11. Matrix multiplication (dot product)
print("Dot Product:\n", np.dot(b, o))

# 12. Mean
print("Mean of a:", np.mean(a))

# 13. Median
print("Median of a:", np.median(a))

# 14. Standard deviation
print("Standard deviation of a:", np.std(a))

# 15. Max value
print("Max of c:", np.max(c))

# 16. Min value
print("Min of b:", np.min(b))

# 17. Square of array
print("Square of a:", np.square(a))

# 18. Square root
print("Square root of a:", np.sqrt(a))

# 19. Sum of elements
print("Sum of a:", np.sum(a))

# 20. Cumulative sum
print("Cumulative sum of a:", np.cumsum(a))

# 21. Transpose of matrix
print("Transpose of b:\n", b.T)

# 22. Generate random numbers
rand_arr = np.random.rand(3, 3)
print("Random 3x3 array:\n", rand_arr)

# 23. Flattening a matrix
flat = b.flatten()
print("Flattened b:", flat)

# 24. Check condition (boolean array)
print("a > 2:", a > 2)

# 25. Copy vs view
copy_arr = a.copy()
view_arr = a.view()
a[0] = 99
print("Original a after change:", a)
print("Copy remains same:", copy_arr)
print("View reflects change:", view_arr)

Array a: [1 2 3 4 5]
Array b:
 [[10 20]
 [30 40]]
Shape of b: (2, 2)
Data type of a: int64
Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1.]
 [1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Reshaped a to 5x1:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Sliced a[1:4]: [2 3 4]
Addition a + c: [6 6 6 6 6]
Multiplication a * c: [5 8 9 8 5]
Dot Product:
 [[30. 30.]
 [70. 70.]]
Mean of a: 3.0
Median of a: 3.0
Standard deviation of a: 1.4142135623730951
Max of c: 5
Min of b: 10
Square of a: [ 1  4  9 16 25]
Square root of a: [1.         1.41421356 1.73205081 2.         2.23606798]
Sum of a: 15
Cumulative sum of a: [ 1  3  6 10 15]
Transpose of b:
 [[10 30]
 [20 40]]
Random 3x3 array:
 [[0.67569865 0.37482224 0.8471545 ]
 [0.0980188  0.70890446 0.97788672]
 [0.89730469 0.80564238 0.35806054]]
Flattened b: [10 20 30 40]
a > 2: [False False  True  True  True]
Original a after change: [99  2  3  4  5]
Copy remains same: [1 2 3 4 5]
View reflects change: [99  2  3  4  5]
